### ISSUE TITLE
Add/Review missing Docs from ERP

### ISSUE THREAD

**Issue by jaumef** [gisce/powerp-docs#169]
- [x] giscedata_escila
- [x] giscedata_facturacio_comer
- [x] giscedata_facturacio_distri
- [x] giscedata_facturacio_distri_iese
- [x] giscedata_georef_cne
- [x] giscedata_lectures_disri
- [x] giscedata_revisions_internes
- [ ] ~giscedata_sitel_fact~
- [x] giscedata_telecom

**Comment by MiquelIR** [comment]
All required modules have been documented on the powerp-docs documentation.
