### ISSUE TITLE
Classificar cada informe a la corresponent secció

### ISSUE THREAD

**Issue by ecarreras** [gisce/powerp-docs#24]
A administració pública hi hauria d'haver els següents subapartats:

![image](https://cloud.githubusercontent.com/assets/294235/17847845/9c57a7c8-6850-11e6-99b5-f2f7f4227748.png)
- CNMC
- AEAT
- Gencat

Els informes de facturació haurien d'anar a un subapartat dins de facturació

**Comment by jaumef** [comment]
Crec que ja es va realitzar, tenco la issue
