### ISSUE TITLE
Afegir guia de punts per revisar per fer review a les Pull Requests

### ISSUE THREAD

**Issue by gdalmau** [gisce/powerp-docs#246]
Informació addicional: https://help.github.com/articles/helping-people-contribute-to-your-project/

Afegir punts per revisar a l'hora de fer una review d'una Pull Request. Exemple:

> - [ ] Revisar que les rutes estiguin en castellà
> - [ ] Revisar que els enllaços en català funcionen
> - [ ] Revisar que els enllaços en castellà funcionen
> - [ ] Revisar que les imatges en català es mostren
> - [ ] Revisar que les imatges en castellà es mostren
> - [ ] ...

**Opció 1:** Afegir una guia a la Wiki (o a algun lloc) per crear una llista d'apartats a revisar a l'hora de fer una pull request. 

**Opció 2:** També es pot fer un "template" per defecte en la pull request. Això fa que quan es crea la pull request apareixen les coses que s'han d'emplenar i es podrien posar els punts anteriors. Info: [Creating a pull request template for your repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository)

**Comment by jaumef** [comment]
Fet via hooks
