### ISSUE TITLE
Separar documentació ATR en seccions

### ISSUE THREAD

**Issue by jaumef** [gisce/powerp-docs#272]
La pàgina de documentació ATR (https://manuals.gisce.net/base/atr/) és molt gran.

Estaria bé separar en seccions (diferents fitxers) aquesta documentació

**Comment by polsala** [comment]
@jaumef @eberloso  
Crec que es podria separar en les següents seccions (fitxers):
- Visió general 
- Manual de funcionament
- Gestió de fitxers xml
- Generació de casos
- Power mail
- Anexes

com ho veieu? (PD: titols no definitius)

**Comment by jaumef** [comment]
@polsala Seria:
Has de fer els títols en `mkdocs.yml` i `mkdocs_es.yml` amb les següents seccions i fitxers:
(cal crear la carpeta gestionatr dins de on es troba gestionatr.md i moure els strings dels resources de les imatges)
```yml
  - Gestió ATR (/docs.../gestionatr.md). Hi poses introducció, conceptes, configuració i doc específica.
  - Gestió ATR:
    - Funcionament General
    - Notificacions
    - ...
    - (Un fitxer per cada H2)
    - Apèndix
```
