### ISSUE TITLE
La url no surt bé

### ISSUE THREAD

**Issue by ecarreras** [gisce/powerp-docs#48]
La URL que es posa en els comentaris no està bé 
![image](https://cloud.githubusercontent.com/assets/294235/19378476/2118826e-91ed-11e6-82a4-8a37220d2a24.png)

**Comment by jaumef** [comment]
S'hauria de testejar, pero en principi ja estaria :+1: 

Quan es faci un altre pull podrem probar, sino es podria probar reenviant un hook de push :+1: 

PR pendent de merge quan es provi: https://github.com/gisce/hookshub/pull/35
