### ISSUE TITLE
.POT doesn't have new strings

### ISSUE THREAD

**Issue by asimon91** [gisce/powerp-docs#62]
.POT file is not getting updated when building documentation with mkdocs build command.

**Comment by ecarreras** [comment]
I need an example please, because in other cases is correctly generated

**Comment by ecarreras** [comment]
Please an example or I'll close the issue

**Comment by asimon91** [comment]
Since november 10th i've not encountered any issues with mkdocs build, so issue can be closed. If I have problems again i'll post an example in order to correctly locate the issue.
