### ISSUE TITLE
Posar la data en que s'ha fet la pàgina i hash del commit

### ISSUE THREAD

**Issue by ecarreras** [gisce/powerp-docs#67]
Estaria bé a peu de pàgina de la documentació poder posar la data de construcció de la pàgina i el hash del commit.

**Comment by jaumef** [comment]
https://github.com/mkdocs/mkdocs/issues/261
Append "copyright" on _mkdocs.yml_ and _mkdocs_es.yml_ before mkdocs build?
Or maybe change the theme?

**Comment by ecarreras** [comment]
But appending the "copyrithg" is not going to work because we want the date of the build, the copyright is static content

**Comment by jaumef** [comment]
We could append it on hookshub build before mkdocs build, getting the date and the hash from the hook.
How do you suggest to proceed?

**Comment by ecarreras** [comment]
I don't know, maybe we can ask to mkdocs community

**Comment by jaumef** [comment]
Found this on my way looking for a solution:

**Comment by jaumef** [comment]
Maybe using this comment we can implement an extra_javascript to add the text to the footer?

The alternative would be to fork the theme and add it there using context variables
