### ISSUE TITLE
Compile pofile before mkdocs build

### ISSUE THREAD

**Issue by jaumef** [gisce/powerp-docs#72]
*.mo file should be commited after *.po file update. If not updated, the mkdocs build won't print the new translations.

It can be pretty interesting to:

- Update hooks to build pofile before mkdocs
- Add new case on test checking mofile is updated

**Comment by ecarreras** [comment]
Maybe this could be a feature of mkdocs-i18n extension

**Comment by jaumef** [comment]
Sure. Mkdocs build (using markdown-i18n) updating the mofile would solve this

**Comment by ecarreras** [comment]
Done in https://github.com/gisce/markdown-i18n/pull/28
