### ISSUE TITLE
Links not working on translations

### ISSUE THREAD

**Issue by Xevib** [gisce/powerp-docs#74]
The translation on spanish of the headers dont mantain the id  so the links don't work on the translated version:
Example
[ES link](http://builds.gisce.net/powerp-docs/powerp_imp_cnmc_resolucio_4131/es/distri/adm-pub/cnmc/#inventari-4131)
[CA link](http://builds.gisce.net/powerp-docs/powerp_imp_cnmc_resolucio_4131/ca/distri/adm-pub/cnmc/#inventari-4131)

Generated html:
On ES:
``` html
<h2>Inventario 4131</h2>
```
On CA:
```  html
<h2 id="inventari-4131">Inventari 4131</h2>
```

**Comment by ecarreras** [comment]
I think this is an issue related to [markdown-i18n extension](https://github.com/gisce/markdown-i18n)
