### ISSUE TITLE
Notes not beeing translated

### ISSUE THREAD

**Issue by Xevib** [gisce/powerp-docs#75]
The notes are not beeing translated even it's on the po file

[Example](http://builds.gisce.net/powerp-docs/powerp_imp_cnmc_resolucio_4131/es/distri/adm-pub/cnmc/)

Original:
https://github.com/gisce/powerp-docs/pull/73/files#diff-d963491fd9ae492a53356b9afdf5a1c3R10581
Translated:
https://github.com/gisce/powerp-docs/pull/73/files#diff-d963491fd9ae492a53356b9afdf5a1c3R10619
Result:
![image](https://cloud.githubusercontent.com/assets/2422305/21148661/3f09537a-c159-11e6-951c-d1f6f995a584.png)

**Comment by ecarreras** [comment]
This is also an issue to [markdown-i18n extension](https://github.com/gisce/markdown-i18n)

**Comment by ecarreras** [comment]
@Xevib with the new version of markdown-i18n (1.1.0) the admonition tests should be translated.
